name: Run Tests

on:
  push:
    branches:
      - '*feature/testWorkflow*' 


#  pull_request:
#     branches:
#       - main
#       - develop 

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: davidsr
        password: ${{secrets.DOCKER_PUBLIC_READ_TOKEN}}

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Set this to your required .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Integration Tests
      run: dotnet test --no-build